apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - homepage.njyzy.space
  #     secretName: homepage-tls
  rules:
  - host: homepage.njyzy.space
    http:
      paths:
      - path: /()?
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 80
      - path: /argo(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: argocd-server.argocd
            port:
              number: 80
      - path: /grafana(/|$)(.*)
        pathType: Prefix
        backend:
          service: 
            name: kube-prometheus-stack-grafana.monitoring
            port:
              number: 80
      - path: /jellyfin(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: jellyfin.media
            port:
              number: 8096
      - path: /hubble(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hubble-ui.kube-system
            port:
              number: 80
