apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - service-account.yaml
  - service.yaml
  - deployment.yaml
  - configmap.yaml
  - cert.yaml
  
commonLabels:
  app.kubernetes.io/name: homepage
  app.kubernetes.io/instance: homepage
