apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 78.1.0
    helm:
      values: |
        crds:
          enabled: true
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kube-state-metrics:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        prometheusOperator:
          enabled: false
        prometheus:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
