apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/zycheny/argo-apps.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'monitoring'
      server: '*'
    - namespace: 'loki'
      server: '*'
    - namespace: 'fluent'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'