apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.7.27
    releaseName: postgresql
    valuesInline:
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            password: immich
      primary:
        containerSecurityContext:
          readOnlyRootFilesystem: false
        initdb:
          scripts:
            create-extensions.sql: |
              CREATE EXTENSION cube;
              CREATE EXTENSION earthdistance;
              CREATE EXTENSION vectors;