apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/zycheny/argo-apps.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'immich'
      server: '*'
    - namespace: 'jellyfin'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'