apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    namespace: cert-manager
    version: v1.19.1
    releaseName: cert-manager
    valuesFile: values.yaml
