# This db is dependent on cloudnative-pg operator being installed in the cluster.
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  # You will need to update your application to use the service name ({clustername}-rw).  
  name: authelia-database
spec:
  instances: 1

  storage:
    size: 1Gi
    # pvcTemplate:
    #   storageClassName: proxmox-csi
    #   volumeName: pv-authelia-postgres
    #   accessModes:
    #     - ReadWriteOnce

  # monitoring:
  #   enablePodMonitor: true

  bootstrap:
    initdb:
      database: authelia
      owner: authelia
      secret:
        name: authelia-database-secret
    