apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    version: 0.10.47
    releaseName: authelia
    valuesFile: values.yaml