pod:
  env: [ { name: TZ, value: Asia/Shanghai } ]
  extraVolumeMounts:
    - name: users
      mountPath: /config/users.yaml
      subPath: users.yaml
  extraVolumes:
    - name: users
      secret: { secretName: users }


# persistence:
#   enabled: true
#   size: 100Mi

configMap:
  storage:
    postgres:
      enabled: true
      deploy: false
      address: authelia-postgres-rw:5432
      database: authelia
      username: authelia
      password:
        secret_name: authelia-postgres-secret
  session:
    cookies:
      - domain: 'auth.njyzy.space'
        default_redirection_url: 'http://homepage.njyzy.space'
  notifier:
    filesystem:
      enabled: true
  access_control:
    default_policy: deny
    rules:
      - domain: '*.njyzy.space'
        policy: one_factor
  authentication_backend:
    file: 
      enabled: true
      path: /config/users.yaml
secret:
  additionalSecrets:
    authelia-postgres-secret:
      items: [ { key: password, path: storage.postgres.password.txt } ]
