pod:
  env: [ { name: TZ, value: Asia/Shanghai } ]
  extraVolumeMounts:
    - name: users
      mountPath: /config/users.yaml
      subPath: users.yaml
  extraVolumes:
    - name: users
      secret: { secretName: users }


# persistence:
#   enabled: true
#   size: 100Mi

configMap:
  storage:
    postgres:
      enabled: true
      deploy: false
      address: authelia-database-rw:5432
      database: authelia
      username: authelia
      password:
        secret_name: authelia-database-app
  session:
    cookies:
      - domain: 'njyzy.space'
        default_redirection_url: 'https://homepage.njyzy.space'
  notifier:
    filesystem:
      enabled: true
  access_control:
    default_policy: deny
    rules:
      - domain_regex: '^.*\.njyzy.space$'
        policy: deny
  authentication_backend:
    file: 
      enabled: true
      path: /config/users.yaml
secret:
  additionalSecrets:
    authelia-database-app:
      items: [ { key: password, path: storage.postgres.password.txt } ]
