persistence:
  enabled: true
  size: 100Mi

configMap:
  storage:
    local:
      enabled: true
  session:
    cookies: [ { domain: njyzy.space } ]
      # - subdomain: 'auth'
      # - domain: 'njyzy.space'

ingress:
  enabled: true
  gatewayAPI:
    enabled: true