# persistence:
#   enabled: true
#   size: 100Mi

configMap:
  storage:
    local:
      enabled: true
    # postgres:
    #   enabled: true
    #   deploy: false
    #   address: tcp://authelia-postgres-rw:5432
    #   database: authelia
    #   username: authelia
    #   password: { secret_name: authelia-postgres-app }
  session:
    # cookies: [ { domain: 127.0.0.1 } ]
    cookies:
      - domain: 'auth.njyzy.space'
  notifier:
    filesystem: { enabled: true }
  access_control:
    default_policy: deny
    rules:
      - domain: '*.njyzy.space'
        policy: one_factor
  authentication_backend:
    file: { enabled: true }
