pod:
  env: [ { name: TZ, value: Asia/Shanghai } ]
  extraVolumeMounts:
    - name: users
      mountPath: /config/users.yaml
      subPath: users.yaml
  extraVolumes:
    - name: users
      secret: { secretName: users }


# persistence:
#   enabled: true
#   size: 100Mi

configMap:
  storage:
    local:
      enabled: true
    # postgres:
    #   enabled: true
    #   deploy: false
    #   address: tcp://authelia-postgres-rw:5432
    #   database: authelia
    #   username: authelia
    #   password: { secret_name: authelia-postgres-app }
  session:
    # cookies: [ { domain: 127.0.0.1 } ]
    cookies:
      - domain: 'njyzy.space'
        subdomain: 'auth'
  notifier:
    filesystem:
      enabled: true
  access_control:
    default_policy: deny
    rules:
      - domain: '*.njyzy.space'
        policy: one_factor
  authentication_backend:
    file: 
      enabled: true
      path: /config/users.yaml
