persistence:
  enabled: true
  size: 100Mi

configMap:
  storage:
    local:
      enabled: true
  session:
    cookies:
      - subdomain: 'auth'
      - domain: 'njyzy.space'

ingress:
  enabled: true
  gatewayAPI:
    enabled: true