apiVersion: v1
kind: Secret
metadata:
  name: immich-database-app
type: Opaque # Standard type for user-defined data
stringData:
  host: immich-database-rw
  user: immich
  password: immich
  dbname: immich