apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.10.1
    releaseName: immich
    valuesFile: values.yaml