apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
  namespace: default
spec:
  secretName: homepage-cert
  dnsNames:
    - homepage.njyzy.space
  issuerRef:
    name: ca-issuer   # or your cluster issuer
    kind: ClusterIssuer
