apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  
helmCharts:
  - name: sealed-secrets
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 2.5.19
    releaseName: sealed-secrets-controller
    namespace: sealed-secrets
    includeCRDs: true
    valuesFile: values.yaml