apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

resources:
  - ns.yaml
  
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.42.0
    releaseName: loki
    valuesFile: values.yaml