apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - rbac.yaml
helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.54.0
    releaseName: fluent-bit
    valuesFile: values.yaml