apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: homarr
    repo: https://homarr-labs.github.io/charts/
    version: 7.1.0
    releaseName: homarr
    valuesInline:
      service:
        type: LoadBalancer
