apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: homarr
    repo: https://homarr-labs.github.io/charts/
    version: 7.1.0
    releaseName: homarr
    valuesInline:
      env:
        TZ: Asia/Shanghai     
        LOG_LEVEL: "info"
      envSecrets:
          # The name of DB Credentials existing secret
        dbCredentials:
          # -- Name of existing secret containing DB credentials
          # Have to be created before applying this kustomization
          existingSecret: "db-secret"
      service:
        type: LoadBalancer
  
