# This db is dependent on cloudnative-pg operator being installed in the cluster.
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  # You will need to update your application to use the service name ({clustername}-rw).  
  name: immich-database
spec:
  instances: 1

  storage:
    size: 1Gi

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries: 
     - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
    
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
type: kubernetes.io/basic-auth
stringData:
  username: immich # required field for kubernetes.io/basic-auth
  password: immich # required field for kubernetes.io/basic-auth