apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/zycheny/argo-apps.git
        revision: HEAD
        directories:
          - path: apps/network/*
  template:
    metadata:
      name: '{{ path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: network
      source:
        repoURL: https://github.com/zycheny/argo-apps.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true