apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/zycheny/argo-apps.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'gateway'
      server: '*'
    - namespace: 'networking'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'