apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    version: 2.3.0
    releaseName: jellyfin
    valuesInline:
      persistence:
        media:
          existingClaim: jellyfin-pvc
      service:
        type: LoadBalancer
