apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - httproute.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    namespace: monitoring
    version: 78.1.0
    releaseName: kube-prometheus-stack
    valuesFile: values.yaml